In [ ]:
import numpy as np

## np.random.randn

In [8]:
np.random.randn(5)

array([-0.42165955, -0.01375514,  0.33743805, -0.62485303, -1.04548363])

In [9]:
np.random.randn(5,5)

array([[-0.98571851, -0.06199118,  0.60860851, -0.61214346,  0.54720795],
       [ 0.67151229,  0.86790661,  0.76483839,  0.44049431, -1.75292147],
       [ 0.85879002, -1.00095114, -0.51242143, -0.75943629, -1.6431572 ],
       [ 0.33098289,  0.66853151, -0.94359994, -1.16385306, -0.29759488],
       [ 0.55200015,  0.68136181, -1.44767133,  0.19428424,  1.48079715]])

## np.random.randint

In [16]:
#np.random.randint(başla,bitir,aralık)

In [23]:
np.random.randint(10)

9

In [24]:
np.random.randint(1,10,2)

array([6, 5])

## np.random.choice

In [43]:
random_dizi = np.random.randint(1,200,10)

In [44]:
random_dizi

array([157, 190, 147, 166,  12, 118, 178,  88, 117, 131])

In [48]:
np.random.choice(random_dizi, size=10)

array([ 12, 157, 117, 131, 178, 157, 190, 178, 157, 147])