In [1]:
import numpy as np

## veri oluşturma

In [10]:
dizi = np.arange(10)
dizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
matris = np.eye(5,dtype= int)
matris

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## slice işlemi

In [24]:
sl_matris = matris[1,:]

In [25]:
sl_matris

array([0, 1, 0, 0, 0])

In [26]:
sl_matris[:] = 99

In [27]:
sl_matris

array([99, 99, 99, 99, 99])

In [28]:
matris[1,:] = 99

In [30]:
matris

array([[ 1,  0,  0,  0,  0],
       [99, 99, 99, 99, 99],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1]])