In [ ]:
import numpy as np

## veri oluşturma

In [29]:
dizi_a = np.arange(1,11)
print(dizi_a)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
dizi_b = np.random.randint(1,20,10)
print(dizi_b)

[ 7  5 12  7  7 15 18  8 17 16]


## işlemler

In [40]:
dizi_c = dizi_a + dizi_b # ayrıca - , * , / , % işlemleri de yapabiliyoruz
print(dizi_c)

[ 8  7 15 11 12 21 25 16 26 26]


## istatistiksel gösterimler

In [45]:
ist_dizi = np.random.randint(1,100,25)
print(ist_dizi)

[35 11 99 71 34 87 35 84 37 30 11 79 63 94 64 62 13 23 88 97 90 61 34 38
 22]


In [54]:
np.sum(ist_dizi) #toplamı

1362

In [55]:
np.mean(ist_dizi) #ortalaması

54.48

In [56]:
np.var(ist_dizi) #varyans

844.9695999999999

In [57]:
np.std(ist_dizi) #standart sapma

29.068360806897935

## kıyaslamalar

In [60]:
dizi_d = np.random.randint(1,500,20)

In [61]:
matris_d = dizi_d.reshape(5,4)

In [62]:
matris_d

array([[342,  15, 194, 305],
       [280, 260, 178, 358],
       [ 21, 428,   8, 140],
       [179, 472,  49,  90],
       [439,  80,  91, 338]])

In [67]:
sonuc_d = matris_d < 200

In [68]:
matris_d[sonuc_d]

array([ 15, 194, 178,  21,   8, 140, 179,  49,  90,  80,  91])