In [1]:
import numpy as np

In [12]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Temel matris özellikleri

In [10]:
print(f"boyut sayısı: {matris.ndim}")

boyut sayısı: 2


In [14]:
matris[0,2]

3

In [17]:
matris[1,1] = 500
matris

array([[  1,   2,   3],
       [  4, 500,   6],
       [  7,   8,   9]])

## Transpoz

In [19]:
matris

array([[  1,   2,   3],
       [  4, 500,   6],
       [  7,   8,   9]])

In [20]:
matris_tr = matris.T

In [21]:
matris_tr

array([[  1,   4,   7],
       [  2, 500,   8],
       [  3,   6,   9]])